import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Summarist Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <nav className="nav">
          <div className="nav__wrapper">
            <figure className="nav__img--mask">
              <img
                className="nav__img"
                src="https://summarist.vercel.app/_next/static/media/logo.1b1c490b.png"
                alt="logo"
              />
            </figure>
            <ul className="nav__list--wrapper">
              <li className="nav__list nav__list--mobile">About</li>
              <li className="nav__list nav__list--mobile">Contact</li>
              <li className="nav__list nav__list--mobile">Help</li>
              <li className="nav__list nav__list--login">
                <Navbar />
              </li>
            </ul>
          </div>
        </nav>
        {children}        
      </body>
    </html>
  );
}
